---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      - id: no-commit-to-branch
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.11
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
        files: ^examples/
      - id: goimports
      - id: gofmt
      - id: golint
      - id: tflint
        files: ^examples/.*\.tf
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_docs
      - id: terraform_tfsec
      - id: checkov
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.15.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
